### ISSUE TITLE
Cant download .ovpn file, connection instantly closes

### ISSUE THREAD

**Issue by alimertcakar** [dockovpn/dockovpn#130]
run:
` docker run --cap-add=NET_ADMIN -it -p 1194:1194/udp -p 8080:8080/tcp -e HOST_ADDR=$(curl -s https://api.ipify.org) alekslitvinenk/openvpn`

than` wget http://95.179.171.54:8080    `

wget : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote
host.
At line:1 char:1
+ wget http://95.179.171.54:8080
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

It does not wait for me to download the file, immediately closes. Tested with chrome and wget

**Comment by tnagels** [comment]
I would think this is an issue specific to your situation; for me it works on Chrome (OSX and Win) and Edge. Are you sure the server is running? Can you see that in the logs?

**Comment by alimertcakar** [comment]
> I would think this is an issue specific to your situation; for me it works on Chrome (OSX and Win) and Edge. Are you sure the server is running? Can you see that in the logs?

Yes, I'll check with another browser. Maybe its an extension causing it, low chance but still.

**Comment by alekslitvinenk** [comment]
Hello!
What server do you use to run docker containers? Make sure the firewall is disabled, or appropriate rules are set
