### ISSUE TITLE
Do not download the file client.ovpn

### ISSUE THREAD

**Issue by wpresources** [dockovpn/dockovpn#148]
When I run the command the app says successful

Sat Dec 4 11:34:36 2021 Config server started, download your client.ovpn config at http://185.80.234.52/

I visited http://185.80.234.52/ and http://185.80.234.52:8080/ but got error ERR_CONNECTION_REFUSED.My VPS root@185.80.234.52 pass 1234567.Please help me

**Comment by Tpona** [comment]
Hi! I got the same issue, have solution?

**Comment by Tpona** [comment]
My solution:
docker run -it --rm --cap-add=NET_ADMIN -p 1194:1194/udp -p **8081**:8080/tcp -e HOST_ADDR=$(curl -s https://api.ipify.org) --name dockovpn alekslitvinenk/openvpn

Just change binding for  8080 port.
From 80 to 8081

**Comment by alekslitvinenk** [comment]
Yes, it looks like the port was busy with another service

**Comment by alekslitvinenk** [comment]
And I would generally suggest to make sure Firewall is disabled. If you're using Ubuntu, you can run:
`ufw disable`

**Comment by lvlrSajjad** [comment]
@alekslitvinenk I have the same issue.
I'm trying to turn my mac mini into a VPN server but I cannot download the config file.
```
docker run -it --rm --cap-add=NET_ADMIN \
-p 1194:1194/udp -p 80:8080/tcp \
-e HOST_ADDR=$(curl -s https://api.ipify.org) \
--name dockovpn alekslitvinenk/openvpn
```
I can execute this command successfully, however, when I try to download from the given ip and port (Usually 80) I can't download the file and when I try to open it on the mac mini it opens the modem's interface.
