### ISSUE TITLE
Change Port 1194

### ISSUE THREAD

**Issue by kazemsoft** [dockovpn/dockovpn#149]
Dear sir, please let me know how can i change default connection port (1194).
because of censorship policy in our country some of isps block port 1194.

**Comment by Toliak** [comment]
Hello
Have you tried to change docker-forwarded port? Line `-p 1194:1194/udp` to, for example, `-p 9999:1194/udp`.
So, the full start script will be:
```
docker run -it --rm --cap-add=NET_ADMIN \
-p 9999:1194/udp -p 80:8080/tcp \
-e HOST_ADDR=$(curl -s https://api.ipify.org) \
--name dockovpn alekslitvinenk/openvpn
```

**Comment by ates** [comment]
https://github.com/dockovpn/dockovpn/pull/163
