### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by ririko5834** [dockovpn/dockovpn#183]
How can I start also Web UI on custom port? It only lets me download config, but I cant access that dashboard.

It isn't included?
https://openvpn.net/vpn-server-resources/how-to-configure-openvpn-as-with-admin-web-ui/

**Comment by alekslitvinenk** [comment]
Hi! The feature in the link you attached is a feature of OpenVPN Access Server which is not an open-source software.
Instead, in the coming releases we will introduce our own web-UI implementation

**Comment by 0xorial** [comment]
@alekslitvinenk, could you share your opinion about this one? https://github.com/d3vilh/openvpn-ui
