### ISSUE TITLE
How do I create the config file only once?

### ISSUE THREAD

**Issue by ahushh** [dockovpn/dockovpn#194]
I ran
```
docker run -it --rm --cap-add=NET_ADMIN \
-p 1194:1194/udp -p 80:8080/tcp \
-e HOST_ADDR=$(curl -s https://api.ipify.org) \
--name dockovpn alekslitvinenk/openvpn
```
Then I downloaded the .ovpn config, imported it into Tunnelblick, connected, and everything worked fine. Then, I stopped the docker container, started it again, and the config no longer worked. I had to download a new one and import it again. I'd prefer if my previous config were preserved between stopping/starting the docker container instead of having to download and import it again and again. Is this possible? I tried to specify a volume as described in the README, but it still created a new config file.

**Comment by alekslitvinenk** [comment]
Hi,

This is how it supposed to work. For consistency between runs, try to
remove —rm option, which deletes container once it stopped

**Comment by ahushh** [comment]
Ah, didn't notice --rm option at first and didn't event expect such way of using docker. Though there probably should be a quick reference on further usage (commands like `docker container stop dockovpn` and  `docker container start dockovpn`) in the README. Great software btw and thank you for your assistance.
