### ISSUE TITLE
Connect to host via SSH

### ISSUE THREAD

**Issue by aleksas** [dockovpn/dockovpn#201]
I've deployed a DockOvpn and I want to connect to host running ovpn docker container via ssh. I tried to connect via the VPN ip (both inet addr and p-2-p addr) that is shown in ifconfig for the tun0 interface within ovpn container, but connection could not be established.  The goal is to ssh jump via the dockovpn into computers in local network.

**Comment by alekslitvinenk** [comment]
Hi! Dockovpn container doesn't have openssh, hence it's not capable of handling SSH connections on it's own. You need to connect to machine which has openssh installed and which is within Dockovpn network.

**Comment by aleksas** [comment]
I have a running ssh server on docker host. Setting network mode to host worked as a charm.
