### ISSUE TITLE
[Question] Compatibility with network_mode: "host"

### ISSUE THREAD

**Issue by scmanjarrez** [dockovpn/dockovpn#220]
Hi, 
Is it possible to run this container using network_mode: "host"? When I'm connected to the VPN, I can't connect to services running in other docker networks, they're dropped due to docker network isolation policies.

**Comment by alekslitvinenk** [comment]
Hi @scmanjarrez 

Thanks a lot for submitting this issue
We apologise we not coming sooner with assistance as we are currently developing developing Dockovpn solution for Kubernetes

With `--network=host` it's not possible forward ports from host to container so it's not possible to download the config and communicate with the tunnel port  from outside. Ports that container use can be accessed via `localhost` only, i.g: `localhost:8080`. Thus links in generated config file will not work

**Comment by UlyssesZh** [comment]
@alekslitvinenk When setting `network_mode: host`, I cannot get devices connected to the VPN have access to the internet. How to solve this problem?
