### ISSUE TITLE
docker-compose  run  fail    

### ISSUE THREAD

**Issue by Seriels** [dockovpn/dockovpn#226]
i   run  docker-compose   
![image](https://github.com/dockovpn/dockovpn/assets/33693501/61e26775-0144-4b42-b342-156b19f88724)

but   logs   is  
![image](https://github.com/dockovpn/dockovpn/assets/33693501/2cd5c92e-a884-4871-9d17-fdc63991ce00)

how do  running is   success

**Comment by hrvylein** [comment]
can confirm that it's broken

**Comment by hrvylein** [comment]
Add `command: ["-r"]` to your docker-compose.yaml and it will start to work. It isn't actually broken but the documentation is not clear how to properly start the container.

**Comment by Seriels** [comment]
Thanks, adding this command after running docker-compose is successful
