### ISSUE TITLE
crl  expired

### ISSUE THREAD

**Issue by sohag033** [dockovpn/dockovpn#229]
Dear concern,
I am using docker-compose and it has been working since last year but now it show ----

dockovpn    | 2023-12-26 08:26:59 103.240.249.198:49858 OpenSSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed
dockovpn    | 2023-12-26 08:26:59 103.240.249.198:49858 TLS_ERROR: BIO read tls_read_plaintext error
dockovpn    | 2023-12-26 08:26:59 103.240.249.198:49858 TLS Error: TLS object -> incoming plaintext read error
dockovpn    | 2023-12-26 08:26:59 103.240.249.198:49858 TLS Error: TLS handshake failed
dockovpn    | 2023-12-26 08:27:36 103.240.249.198:54878 VERIFY ERROR: depth=0, error=CRL has expired: CN=YDX2DP98TrAYtgxQ6DbZ9J7oeTis1Rci, serial=81233966551556699061380766434104177286
dockovpn    | 2023-12-26 08:27:36 103.240.249.198:54878 OpenSSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed
dockovpn    | 2023-12-26 08:27:36 103.240.249.198:54878 TLS_ERROR: BIO read tls_read_plaintext error
dockovpn    | 2023-12-26 08:27:36 103.240.249.198:54878 TLS Error: TLS object -> incoming plaintext read error
dockovpn    | 2023-12-26 08:27:36 103.240.249.198:54878 TLS Error: TLS handshake failed
dockovpn    | 2023-12-26 08:27:41 103.240.249.198:58478 VERIFY ERROR: depth=0, error=CRL has expired: CN=ouAjgNC1cVR051jbz97DNF1MtYvDwwGS, serial=78283103143308444084962227741182079977
dockovpn    | 2023-12-26 08:27:41 103.240.249.198:58478 OpenSSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed
dockovpn    | 2023-12-26 08:27:41 103.240.249.198:58478 TLS_ERROR: BIO read tls_read_plaintext error
dockovpn    | 2023-12-26 08:27:41 103.240.249.198:58478 TLS Error: TLS object -> incoming plaintext read error
dockovpn    | 2023-12-26 08:27:41 103.240.249.198:58478 TLS Error: TLS handshake failed
dockovpn    | 2023-12-26 08:27:59 103.240.249.198:60480 VERIFY ERROR: depth=0, error=CRL has expired: CN=ouAjgNC1cVR051jbz97DNF1MtYvDwwGS, serial=78283103143308444084962227741182079977
dockovpn    | 2023-12-26 08:27:59 103.240.249.198:60480 OpenSSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed
dockovpn    | 2023-12-26 08:27:59 103.240.249.198:60480 TLS_ERROR: BIO read tls_read_plaintext error
dockovpn    | 2023-12-26 08:27:59 103.240.249.198:60480 TLS Error: TLS object -> incoming plaintext read error
dockovpn    | 2023-12-26 08:27:59 103.240.249.198:60480 TLS Error: TLS handshake failed

My docker-compose is also provide below -
version: '3'

services:
  dockovpn:
    image: alekslitvinenk/openvpn
    container_name: dockovpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
      - 80:8080/tcp
    environment:
      - HOST_ADDR=apvpn.amiprobashi.com
      - OPENVPN_MTU=1470
    volumes:
      - openvpn_conf:/opt/Dockovpn_data

volumes:
  openvpn_conf:
  
  could you please help me to get rid of it?

**Comment by scmanjarrez** [comment]
Related to #181. I posted a fix in https://github.com/dockovpn/dockovpn/issues/181#issuecomment-1875825981

**Comment by alekslitvinenk** [comment]
Fixed by @scmanjarrez in #242
